name: Code Review Suggestions

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Make code suggestions
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            async function makeCodeSuggestion() {
              const { owner, repo } = context.repo;
              const pull_number = context.payload.pull_request.number;
              
              await github.rest.pulls.createReviewComment({
                owner,
                repo,
                pull_number,
                commit_id: context.payload.pull_request.head.sha,
                path: 'src/components/logs/LogEntry.tsx',
                line: 50,
                body: '```suggestion\n            <div className="mt-2 p-2 bg-red-50 rounded text-sm overflow-x-auto font-mono">\n```\n'
              });
            }
            
            await makeCodeSuggestion();
